// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // Authenticated user (follower)
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // User to follow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{2}
}

func (x *FollowRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // Authenticated user (follower)
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // User to unfollow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfollowRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // Authenticated user (being followed)
	TargetUserId  uint64                 `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // Follower to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FollowResource      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowersResponse) GetData() []*FollowResource {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FollowResource      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowingResponse) GetData() []*FollowResource {
	if x != nil {
		return x.Data
	}
	return nil
}

type FollowResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ProfilePhotos []string               `protobuf:"bytes,4,rep,name=profile_photos,json=profilePhotos,proto3" json:"profile_photos,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Online        bool                   `protobuf:"varint,6,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResource) Reset() {
	*x = FollowResource{}
	mi := &file_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResource) ProtoMessage() {}

func (x *FollowResource) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResource.ProtoReflect.Descriptor instead.
func (*FollowResource) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{7}
}

func (x *FollowResource) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FollowResource) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FollowResource) GetProfilePhotos() []string {
	if x != nil {
		return x.ProfilePhotos
	}
	return nil
}

func (x *FollowResource) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *FollowResource) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type GetTimingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimingsRequest) Reset() {
	*x = GetTimingsRequest{}
	mi := &file_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimingsRequest) ProtoMessage() {}

func (x *GetTimingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimingsRequest.ProtoReflect.Descriptor instead.
func (*GetTimingsRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{8}
}

type GetTimingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TimingsData           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimingsResponse) Reset() {
	*x = GetTimingsResponse{}
	mi := &file_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimingsResponse) ProtoMessage() {}

func (x *GetTimingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimingsResponse.ProtoReflect.Descriptor instead.
func (*GetTimingsResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{9}
}

func (x *GetTimingsResponse) GetData() *TimingsData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TimingsData struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DisplayAdInterval       int32                  `protobuf:"varint,1,opt,name=display_ad_interval,json=displayAdInterval,proto3" json:"display_ad_interval,omitempty"`
	DisplayQuestionInterval int32                  `protobuf:"varint,2,opt,name=display_question_interval,json=displayQuestionInterval,proto3" json:"display_question_interval,omitempty"`
	DisplayAnswerInterval   int32                  `protobuf:"varint,3,opt,name=display_answer_interval,json=displayAnswerInterval,proto3" json:"display_answer_interval,omitempty"`
	Participants            int32                  `protobuf:"varint,4,opt,name=participants,proto3" json:"participants,omitempty"`
	CorrectAnswers          int32                  `protobuf:"varint,5,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	WrongAnswers            int32                  `protobuf:"varint,6,opt,name=wrong_answers,json=wrongAnswers,proto3" json:"wrong_answers,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TimingsData) Reset() {
	*x = TimingsData{}
	mi := &file_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingsData) ProtoMessage() {}

func (x *TimingsData) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingsData.ProtoReflect.Descriptor instead.
func (*TimingsData) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{10}
}

func (x *TimingsData) GetDisplayAdInterval() int32 {
	if x != nil {
		return x.DisplayAdInterval
	}
	return 0
}

func (x *TimingsData) GetDisplayQuestionInterval() int32 {
	if x != nil {
		return x.DisplayQuestionInterval
	}
	return 0
}

func (x *TimingsData) GetDisplayAnswerInterval() int32 {
	if x != nil {
		return x.DisplayAnswerInterval
	}
	return 0
}

func (x *TimingsData) GetParticipants() int32 {
	if x != nil {
		return x.Participants
	}
	return 0
}

func (x *TimingsData) GetCorrectAnswers() int32 {
	if x != nil {
		return x.CorrectAnswers
	}
	return 0
}

func (x *TimingsData) GetWrongAnswers() int32 {
	if x != nil {
		return x.WrongAnswers
	}
	return 0
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{11}
}

func (x *GetQuestionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *QuestionResource      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{12}
}

func (x *GetQuestionResponse) GetData() *QuestionResource {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubmitAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId    uint64                 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerId      uint64                 `protobuf:"varint,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitAnswerRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitAnswerRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *SubmitAnswerRequest) GetAnswerId() uint64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *QuestionResource      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitAnswerResponse) GetData() *QuestionResource {
	if x != nil {
		return x.Data
	}
	return nil
}

type QuestionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Prize         int32                  `protobuf:"varint,4,opt,name=prize,proto3" json:"prize,omitempty"`
	Participants  int32                  `protobuf:"varint,5,opt,name=participants,proto3" json:"participants,omitempty"`
	Views         int32                  `protobuf:"varint,6,opt,name=views,proto3" json:"views,omitempty"`
	CreatorCode   string                 `protobuf:"bytes,7,opt,name=creator_code,json=creatorCode,proto3" json:"creator_code,omitempty"`
	Answers       []*AnswerResource      `protobuf:"bytes,8,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionResource) Reset() {
	*x = QuestionResource{}
	mi := &file_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResource) ProtoMessage() {}

func (x *QuestionResource) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResource.ProtoReflect.Descriptor instead.
func (*QuestionResource) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{15}
}

func (x *QuestionResource) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionResource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionResource) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *QuestionResource) GetPrize() int32 {
	if x != nil {
		return x.Prize
	}
	return 0
}

func (x *QuestionResource) GetParticipants() int32 {
	if x != nil {
		return x.Participants
	}
	return 0
}

func (x *QuestionResource) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *QuestionResource) GetCreatorCode() string {
	if x != nil {
		return x.CreatorCode
	}
	return ""
}

func (x *QuestionResource) GetAnswers() []*AnswerResource {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AnswerResource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image          string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	IsCorrect      bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`                // Only present in answer submission response
	VotePercentage int32                  `protobuf:"varint,5,opt,name=vote_percentage,json=votePercentage,proto3" json:"vote_percentage,omitempty"` // Only present in answer submission response
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnswerResource) Reset() {
	*x = AnswerResource{}
	mi := &file_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResource) ProtoMessage() {}

func (x *AnswerResource) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResource.ProtoReflect.Descriptor instead.
func (*AnswerResource) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{16}
}

func (x *AnswerResource) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnswerResource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnswerResource) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AnswerResource) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *AnswerResource) GetVotePercentage() int32 {
	if x != nil {
		return x.VotePercentage
	}
	return 0
}

var File_social_proto protoreflect.FileDescriptor

const file_social_proto_rawDesc = "" +
	"\n" +
	"\fsocial.proto\x12\x06social\x1a\x1bgoogle/protobuf/empty.proto\".\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\".\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"N\n" +
	"\rFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x04R\ftargetUserId\"P\n" +
	"\x0fUnfollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x04R\ftargetUserId\"N\n" +
	"\rRemoveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x04R\ftargetUserId\"B\n" +
	"\x14GetFollowersResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.social.FollowResourceR\x04data\"B\n" +
	"\x14GetFollowingResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.social.FollowResourceR\x04data\"\x9d\x01\n" +
	"\x0eFollowResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12%\n" +
	"\x0eprofile_photos\x18\x04 \x03(\tR\rprofilePhotos\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x16\n" +
	"\x06online\x18\x06 \x01(\bR\x06online\"\x13\n" +
	"\x11GetTimingsRequest\"=\n" +
	"\x12GetTimingsResponse\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.social.TimingsDataR\x04data\"\xa3\x02\n" +
	"\vTimingsData\x12.\n" +
	"\x13display_ad_interval\x18\x01 \x01(\x05R\x11displayAdInterval\x12:\n" +
	"\x19display_question_interval\x18\x02 \x01(\x05R\x17displayQuestionInterval\x126\n" +
	"\x17display_answer_interval\x18\x03 \x01(\x05R\x15displayAnswerInterval\x12\"\n" +
	"\fparticipants\x18\x04 \x01(\x05R\fparticipants\x12'\n" +
	"\x0fcorrect_answers\x18\x05 \x01(\x05R\x0ecorrectAnswers\x12#\n" +
	"\rwrong_answers\x18\x06 \x01(\x05R\fwrongAnswers\"-\n" +
	"\x12GetQuestionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"C\n" +
	"\x13GetQuestionResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.social.QuestionResourceR\x04data\"l\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x04R\n" +
	"questionId\x12\x1b\n" +
	"\tanswer_id\x18\x03 \x01(\x04R\banswerId\"D\n" +
	"\x14SubmitAnswerResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.social.QuestionResourceR\x04data\"\xf3\x01\n" +
	"\x10QuestionResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05prize\x18\x04 \x01(\x05R\x05prize\x12\"\n" +
	"\fparticipants\x18\x05 \x01(\x05R\fparticipants\x12\x14\n" +
	"\x05views\x18\x06 \x01(\x05R\x05views\x12!\n" +
	"\fcreator_code\x18\a \x01(\tR\vcreatorCode\x120\n" +
	"\aanswers\x18\b \x03(\v2\x16.social.AnswerResourceR\aanswers\"\x94\x01\n" +
	"\x0eAnswerResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\x12'\n" +
	"\x0fvote_percentage\x18\x05 \x01(\x05R\x0evotePercentage2\xd4\x02\n" +
	"\rFollowService\x12I\n" +
	"\fGetFollowers\x12\x1b.social.GetFollowersRequest\x1a\x1c.social.GetFollowersResponse\x12I\n" +
	"\fGetFollowing\x12\x1b.social.GetFollowingRequest\x1a\x1c.social.GetFollowingResponse\x127\n" +
	"\x06Follow\x12\x15.social.FollowRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\bUnfollow\x12\x17.social.UnfollowRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x06Remove\x12\x15.social.RemoveRequest\x1a\x16.google.protobuf.Empty2\xea\x01\n" +
	"\x10ChallengeService\x12C\n" +
	"\n" +
	"GetTimings\x12\x19.social.GetTimingsRequest\x1a\x1a.social.GetTimingsResponse\x12F\n" +
	"\vGetQuestion\x12\x1a.social.GetQuestionRequest\x1a\x1b.social.GetQuestionResponse\x12I\n" +
	"\fSubmitAnswer\x12\x1b.social.SubmitAnswerRequest\x1a\x1c.social.SubmitAnswerResponseB\x1aZ\x18metargb/shared/pb/socialb\x06proto3"

var (
	file_social_proto_rawDescOnce sync.Once
	file_social_proto_rawDescData []byte
)

func file_social_proto_rawDescGZIP() []byte {
	file_social_proto_rawDescOnce.Do(func() {
		file_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)))
	})
	return file_social_proto_rawDescData
}

var file_social_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_social_proto_goTypes = []any{
	(*GetFollowersRequest)(nil),  // 0: social.GetFollowersRequest
	(*GetFollowingRequest)(nil),  // 1: social.GetFollowingRequest
	(*FollowRequest)(nil),        // 2: social.FollowRequest
	(*UnfollowRequest)(nil),      // 3: social.UnfollowRequest
	(*RemoveRequest)(nil),        // 4: social.RemoveRequest
	(*GetFollowersResponse)(nil), // 5: social.GetFollowersResponse
	(*GetFollowingResponse)(nil), // 6: social.GetFollowingResponse
	(*FollowResource)(nil),       // 7: social.FollowResource
	(*GetTimingsRequest)(nil),    // 8: social.GetTimingsRequest
	(*GetTimingsResponse)(nil),   // 9: social.GetTimingsResponse
	(*TimingsData)(nil),          // 10: social.TimingsData
	(*GetQuestionRequest)(nil),   // 11: social.GetQuestionRequest
	(*GetQuestionResponse)(nil),  // 12: social.GetQuestionResponse
	(*SubmitAnswerRequest)(nil),  // 13: social.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil), // 14: social.SubmitAnswerResponse
	(*QuestionResource)(nil),     // 15: social.QuestionResource
	(*AnswerResource)(nil),       // 16: social.AnswerResource
	(*emptypb.Empty)(nil),        // 17: google.protobuf.Empty
}
var file_social_proto_depIdxs = []int32{
	7,  // 0: social.GetFollowersResponse.data:type_name -> social.FollowResource
	7,  // 1: social.GetFollowingResponse.data:type_name -> social.FollowResource
	10, // 2: social.GetTimingsResponse.data:type_name -> social.TimingsData
	15, // 3: social.GetQuestionResponse.data:type_name -> social.QuestionResource
	15, // 4: social.SubmitAnswerResponse.data:type_name -> social.QuestionResource
	16, // 5: social.QuestionResource.answers:type_name -> social.AnswerResource
	0,  // 6: social.FollowService.GetFollowers:input_type -> social.GetFollowersRequest
	1,  // 7: social.FollowService.GetFollowing:input_type -> social.GetFollowingRequest
	2,  // 8: social.FollowService.Follow:input_type -> social.FollowRequest
	3,  // 9: social.FollowService.Unfollow:input_type -> social.UnfollowRequest
	4,  // 10: social.FollowService.Remove:input_type -> social.RemoveRequest
	8,  // 11: social.ChallengeService.GetTimings:input_type -> social.GetTimingsRequest
	11, // 12: social.ChallengeService.GetQuestion:input_type -> social.GetQuestionRequest
	13, // 13: social.ChallengeService.SubmitAnswer:input_type -> social.SubmitAnswerRequest
	5,  // 14: social.FollowService.GetFollowers:output_type -> social.GetFollowersResponse
	6,  // 15: social.FollowService.GetFollowing:output_type -> social.GetFollowingResponse
	17, // 16: social.FollowService.Follow:output_type -> google.protobuf.Empty
	17, // 17: social.FollowService.Unfollow:output_type -> google.protobuf.Empty
	17, // 18: social.FollowService.Remove:output_type -> google.protobuf.Empty
	9,  // 19: social.ChallengeService.GetTimings:output_type -> social.GetTimingsResponse
	12, // 20: social.ChallengeService.GetQuestion:output_type -> social.GetQuestionResponse
	14, // 21: social.ChallengeService.SubmitAnswer:output_type -> social.SubmitAnswerResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_social_proto_init() }
func file_social_proto_init() {
	if File_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_social_proto_goTypes,
		DependencyIndexes: file_social_proto_depIdxs,
		MessageInfos:      file_social_proto_msgTypes,
	}.Build()
	File_social_proto = out.File
	file_social_proto_goTypes = nil
	file_social_proto_depIdxs = nil
}
