// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: dynasty.proto

package dynasty

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "metargb/shared/pb/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDynastyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeatureId     uint64                 `protobuf:"varint,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDynastyRequest) Reset() {
	*x = CreateDynastyRequest{}
	mi := &file_dynasty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDynastyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDynastyRequest) ProtoMessage() {}

func (x *CreateDynastyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDynastyRequest.ProtoReflect.Descriptor instead.
func (*CreateDynastyRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDynastyRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateDynastyRequest) GetFeatureId() uint64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

type GetDynastyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DynastyId     uint64                 `protobuf:"varint,1,opt,name=dynasty_id,json=dynastyId,proto3" json:"dynasty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynastyRequest) Reset() {
	*x = GetDynastyRequest{}
	mi := &file_dynasty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynastyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynastyRequest) ProtoMessage() {}

func (x *GetDynastyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynastyRequest.ProtoReflect.Descriptor instead.
func (*GetDynastyRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{1}
}

func (x *GetDynastyRequest) GetDynastyId() uint64 {
	if x != nil {
		return x.DynastyId
	}
	return 0
}

type UpdateDynastyFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DynastyId     uint64                 `protobuf:"varint,1,opt,name=dynasty_id,json=dynastyId,proto3" json:"dynasty_id,omitempty"`
	FeatureId     uint64                 `protobuf:"varint,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDynastyFeatureRequest) Reset() {
	*x = UpdateDynastyFeatureRequest{}
	mi := &file_dynasty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDynastyFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDynastyFeatureRequest) ProtoMessage() {}

func (x *UpdateDynastyFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDynastyFeatureRequest.ProtoReflect.Descriptor instead.
func (*UpdateDynastyFeatureRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDynastyFeatureRequest) GetDynastyId() uint64 {
	if x != nil {
		return x.DynastyId
	}
	return 0
}

func (x *UpdateDynastyFeatureRequest) GetFeatureId() uint64 {
	if x != nil {
		return x.FeatureId
	}
	return 0
}

func (x *UpdateDynastyFeatureRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserDynastyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDynastyRequest) Reset() {
	*x = GetUserDynastyRequest{}
	mi := &file_dynasty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDynastyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDynastyRequest) ProtoMessage() {}

func (x *GetUserDynastyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDynastyRequest.ProtoReflect.Descriptor instead.
func (*GetUserDynastyRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserDynastyRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DynastyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserHasDynasty bool                   `protobuf:"varint,1,opt,name=user_has_dynasty,json=userHasDynasty,proto3" json:"user_has_dynasty,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId       uint64                 `protobuf:"varint,3,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Jalali formatted
	ProfileImage   string                 `protobuf:"bytes,5,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	DynastyFeature *DynastyFeature        `protobuf:"bytes,6,opt,name=dynasty_feature,json=dynastyFeature,proto3" json:"dynasty_feature,omitempty"`
	Features       []*AvailableFeature    `protobuf:"bytes,7,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DynastyResponse) Reset() {
	*x = DynastyResponse{}
	mi := &file_dynasty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynastyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynastyResponse) ProtoMessage() {}

func (x *DynastyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynastyResponse.ProtoReflect.Descriptor instead.
func (*DynastyResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{4}
}

func (x *DynastyResponse) GetUserHasDynasty() bool {
	if x != nil {
		return x.UserHasDynasty
	}
	return false
}

func (x *DynastyResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DynastyResponse) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *DynastyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DynastyResponse) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *DynastyResponse) GetDynastyFeature() *DynastyFeature {
	if x != nil {
		return x.DynastyFeature
	}
	return nil
}

func (x *DynastyResponse) GetFeatures() []*AvailableFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

type DynastyFeature struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertiesId          string                 `protobuf:"bytes,2,opt,name=properties_id,json=propertiesId,proto3" json:"properties_id,omitempty"`
	Area                  string                 `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"`
	Density               string                 `protobuf:"bytes,4,opt,name=density,proto3" json:"density,omitempty"`
	FeatureProfitIncrease string                 `protobuf:"bytes,5,opt,name=feature_profit_increase,json=featureProfitIncrease,proto3" json:"feature_profit_increase,omitempty"`
	FamilyMembersCount    int32                  `protobuf:"varint,6,opt,name=family_members_count,json=familyMembersCount,proto3" json:"family_members_count,omitempty"`
	LastUpdated           string                 `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Jalali formatted
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DynastyFeature) Reset() {
	*x = DynastyFeature{}
	mi := &file_dynasty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynastyFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynastyFeature) ProtoMessage() {}

func (x *DynastyFeature) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynastyFeature.ProtoReflect.Descriptor instead.
func (*DynastyFeature) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{5}
}

func (x *DynastyFeature) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DynastyFeature) GetPropertiesId() string {
	if x != nil {
		return x.PropertiesId
	}
	return ""
}

func (x *DynastyFeature) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *DynastyFeature) GetDensity() string {
	if x != nil {
		return x.Density
	}
	return ""
}

func (x *DynastyFeature) GetFeatureProfitIncrease() string {
	if x != nil {
		return x.FeatureProfitIncrease
	}
	return ""
}

func (x *DynastyFeature) GetFamilyMembersCount() int32 {
	if x != nil {
		return x.FamilyMembersCount
	}
	return 0
}

func (x *DynastyFeature) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type AvailableFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertiesId  string                 `protobuf:"bytes,2,opt,name=properties_id,json=propertiesId,proto3" json:"properties_id,omitempty"`
	Density       string                 `protobuf:"bytes,3,opt,name=density,proto3" json:"density,omitempty"`
	Stability     string                 `protobuf:"bytes,4,opt,name=stability,proto3" json:"stability,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableFeature) Reset() {
	*x = AvailableFeature{}
	mi := &file_dynasty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableFeature) ProtoMessage() {}

func (x *AvailableFeature) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableFeature.ProtoReflect.Descriptor instead.
func (*AvailableFeature) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{6}
}

func (x *AvailableFeature) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AvailableFeature) GetPropertiesId() string {
	if x != nil {
		return x.PropertiesId
	}
	return ""
}

func (x *AvailableFeature) GetDensity() string {
	if x != nil {
		return x.Density
	}
	return ""
}

func (x *AvailableFeature) GetStability() string {
	if x != nil {
		return x.Stability
	}
	return ""
}

func (x *AvailableFeature) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type SendJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Relationship  string                 `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"` // father, mother, offspring, spouse
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Permissions   *ChildPermissions      `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"` // only for offspring relationship
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendJoinRequestRequest) Reset() {
	*x = SendJoinRequestRequest{}
	mi := &file_dynasty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendJoinRequestRequest) ProtoMessage() {}

func (x *SendJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*SendJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{7}
}

func (x *SendJoinRequestRequest) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendJoinRequestRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendJoinRequestRequest) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *SendJoinRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendJoinRequestRequest) GetPermissions() *ChildPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type JoinRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUser      uint64                 `protobuf:"varint,2,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty"`
	ToUser        uint64                 `protobuf:"varint,3,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Relationship  string                 `protobuf:"bytes,5,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ToUserInfo    *common.UserBasic      `protobuf:"bytes,7,opt,name=to_user_info,json=toUserInfo,proto3" json:"to_user_info,omitempty"`
	RequestPrize  *DynastyPrize          `protobuf:"bytes,8,opt,name=request_prize,json=requestPrize,proto3" json:"request_prize,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Jalali formatted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequestResponse) Reset() {
	*x = JoinRequestResponse{}
	mi := &file_dynasty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequestResponse) ProtoMessage() {}

func (x *JoinRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequestResponse.ProtoReflect.Descriptor instead.
func (*JoinRequestResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRequestResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JoinRequestResponse) GetFromUser() uint64 {
	if x != nil {
		return x.FromUser
	}
	return 0
}

func (x *JoinRequestResponse) GetToUser() uint64 {
	if x != nil {
		return x.ToUser
	}
	return 0
}

func (x *JoinRequestResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JoinRequestResponse) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *JoinRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinRequestResponse) GetToUserInfo() *common.UserBasic {
	if x != nil {
		return x.ToUserInfo
	}
	return nil
}

func (x *JoinRequestResponse) GetRequestPrize() *DynastyPrize {
	if x != nil {
		return x.RequestPrize
	}
	return nil
}

func (x *JoinRequestResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetSentRequestsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        uint64                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSentRequestsRequest) Reset() {
	*x = GetSentRequestsRequest{}
	mi := &file_dynasty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSentRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSentRequestsRequest) ProtoMessage() {}

func (x *GetSentRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSentRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetSentRequestsRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{9}
}

func (x *GetSentRequestsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSentRequestsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetReceivedRequestsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        uint64                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceivedRequestsRequest) Reset() {
	*x = GetReceivedRequestsRequest{}
	mi := &file_dynasty_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceivedRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceivedRequestsRequest) ProtoMessage() {}

func (x *GetReceivedRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceivedRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetReceivedRequestsRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{10}
}

func (x *GetReceivedRequestsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetReceivedRequestsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // for authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJoinRequestRequest) Reset() {
	*x = GetJoinRequestRequest{}
	mi := &file_dynasty_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinRequestRequest) ProtoMessage() {}

func (x *GetJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*GetJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{11}
}

func (x *GetJoinRequestRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GetJoinRequestRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type JoinRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*JoinRequestResponse `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequestsResponse) Reset() {
	*x = JoinRequestsResponse{}
	mi := &file_dynasty_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequestsResponse) ProtoMessage() {}

func (x *JoinRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequestsResponse.ProtoReflect.Descriptor instead.
func (*JoinRequestsResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{12}
}

func (x *JoinRequestsResponse) GetRequests() []*JoinRequestResponse {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *JoinRequestsResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AcceptJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptJoinRequestRequest) Reset() {
	*x = AcceptJoinRequestRequest{}
	mi := &file_dynasty_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJoinRequestRequest) ProtoMessage() {}

func (x *AcceptJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptJoinRequestRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AcceptJoinRequestRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RejectJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectJoinRequestRequest) Reset() {
	*x = RejectJoinRequestRequest{}
	mi := &file_dynasty_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectJoinRequestRequest) ProtoMessage() {}

func (x *RejectJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{14}
}

func (x *RejectJoinRequestRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RejectJoinRequestRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJoinRequestRequest) Reset() {
	*x = DeleteJoinRequestRequest{}
	mi := &file_dynasty_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJoinRequestRequest) ProtoMessage() {}

func (x *DeleteJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*DeleteJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteJoinRequestRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DeleteJoinRequestRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	DynastyId     uint64                 `protobuf:"varint,2,opt,name=dynasty_id,json=dynastyId,proto3" json:"dynasty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRequest) Reset() {
	*x = GetFamilyRequest{}
	mi := &file_dynasty_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRequest) ProtoMessage() {}

func (x *GetFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{16}
}

func (x *GetFamilyRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *GetFamilyRequest) GetDynastyId() uint64 {
	if x != nil {
		return x.DynastyId
	}
	return 0
}

type FamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DynastyId     uint64                 `protobuf:"varint,2,opt,name=dynasty_id,json=dynastyId,proto3" json:"dynasty_id,omitempty"`
	Members       []*FamilyMember        `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyResponse) Reset() {
	*x = FamilyResponse{}
	mi := &file_dynasty_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyResponse) ProtoMessage() {}

func (x *FamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyResponse.ProtoReflect.Descriptor instead.
func (*FamilyResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{17}
}

func (x *FamilyResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FamilyResponse) GetDynastyId() uint64 {
	if x != nil {
		return x.DynastyId
	}
	return 0
}

func (x *FamilyResponse) GetMembers() []*FamilyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetFamilyMembersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	FamilyId      uint64                    `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyMembersRequest) Reset() {
	*x = GetFamilyMembersRequest{}
	mi := &file_dynasty_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyMembersRequest) ProtoMessage() {}

func (x *GetFamilyMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyMembersRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyMembersRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{18}
}

func (x *GetFamilyMembersRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *GetFamilyMembersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FamilyMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*FamilyMember        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyMembersResponse) Reset() {
	*x = FamilyMembersResponse{}
	mi := &file_dynasty_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyMembersResponse) ProtoMessage() {}

func (x *FamilyMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyMembersResponse.ProtoReflect.Descriptor instead.
func (*FamilyMembersResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{19}
}

func (x *FamilyMembersResponse) GetMembers() []*FamilyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *FamilyMembersResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FamilyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Relationship  string                 `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"`
	UserInfo      *common.UserBasic      `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Jalali formatted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyMember) Reset() {
	*x = FamilyMember{}
	mi := &file_dynasty_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyMember) ProtoMessage() {}

func (x *FamilyMember) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyMember.ProtoReflect.Descriptor instead.
func (*FamilyMember) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{20}
}

func (x *FamilyMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FamilyMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FamilyMember) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *FamilyMember) GetUserInfo() *common.UserBasic {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *FamilyMember) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SetChildPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildUserId   uint64                 `protobuf:"varint,1,opt,name=child_user_id,json=childUserId,proto3" json:"child_user_id,omitempty"`
	ParentUserId  uint64                 `protobuf:"varint,2,opt,name=parent_user_id,json=parentUserId,proto3" json:"parent_user_id,omitempty"`
	Permissions   *ChildPermissions      `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetChildPermissionsRequest) Reset() {
	*x = SetChildPermissionsRequest{}
	mi := &file_dynasty_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetChildPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChildPermissionsRequest) ProtoMessage() {}

func (x *SetChildPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChildPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetChildPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{21}
}

func (x *SetChildPermissionsRequest) GetChildUserId() uint64 {
	if x != nil {
		return x.ChildUserId
	}
	return 0
}

func (x *SetChildPermissionsRequest) GetParentUserId() uint64 {
	if x != nil {
		return x.ParentUserId
	}
	return 0
}

func (x *SetChildPermissionsRequest) GetPermissions() *ChildPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ChildPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	BFR           bool                   `protobuf:"varint,2,opt,name=BFR,proto3" json:"BFR,omitempty"`    // Buy Feature Request
	SF            bool                   `protobuf:"varint,3,opt,name=SF,proto3" json:"SF,omitempty"`      // Sell Feature
	W             bool                   `protobuf:"varint,4,opt,name=W,proto3" json:"W,omitempty"`        // Wallet
	JU            bool                   `protobuf:"varint,5,opt,name=JU,proto3" json:"JU,omitempty"`      // Join/Unjoin
	DM            bool                   `protobuf:"varint,6,opt,name=DM,proto3" json:"DM,omitempty"`      // Dynasty Management
	PIUP          bool                   `protobuf:"varint,7,opt,name=PIUP,proto3" json:"PIUP,omitempty"`  // Personal Info Update
	PITC          bool                   `protobuf:"varint,8,opt,name=PITC,proto3" json:"PITC,omitempty"`  // Personal Info Type Change
	PIC           bool                   `protobuf:"varint,9,opt,name=PIC,proto3" json:"PIC,omitempty"`    // Personal Info Change
	ESOO          bool                   `protobuf:"varint,10,opt,name=ESOO,proto3" json:"ESOO,omitempty"` // Edit Settings On/Off
	COTB          bool                   `protobuf:"varint,11,opt,name=COTB,proto3" json:"COTB,omitempty"` // Change Of The Birth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildPermissions) Reset() {
	*x = ChildPermissions{}
	mi := &file_dynasty_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildPermissions) ProtoMessage() {}

func (x *ChildPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildPermissions.ProtoReflect.Descriptor instead.
func (*ChildPermissions) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{22}
}

func (x *ChildPermissions) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *ChildPermissions) GetBFR() bool {
	if x != nil {
		return x.BFR
	}
	return false
}

func (x *ChildPermissions) GetSF() bool {
	if x != nil {
		return x.SF
	}
	return false
}

func (x *ChildPermissions) GetW() bool {
	if x != nil {
		return x.W
	}
	return false
}

func (x *ChildPermissions) GetJU() bool {
	if x != nil {
		return x.JU
	}
	return false
}

func (x *ChildPermissions) GetDM() bool {
	if x != nil {
		return x.DM
	}
	return false
}

func (x *ChildPermissions) GetPIUP() bool {
	if x != nil {
		return x.PIUP
	}
	return false
}

func (x *ChildPermissions) GetPITC() bool {
	if x != nil {
		return x.PITC
	}
	return false
}

func (x *ChildPermissions) GetPIC() bool {
	if x != nil {
		return x.PIC
	}
	return false
}

func (x *ChildPermissions) GetESOO() bool {
	if x != nil {
		return x.ESOO
	}
	return false
}

func (x *ChildPermissions) GetCOTB() bool {
	if x != nil {
		return x.COTB
	}
	return false
}

type GetPrizesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        uint64                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrizesRequest) Reset() {
	*x = GetPrizesRequest{}
	mi := &file_dynasty_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrizesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrizesRequest) ProtoMessage() {}

func (x *GetPrizesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrizesRequest.ProtoReflect.Descriptor instead.
func (*GetPrizesRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{23}
}

func (x *GetPrizesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPrizesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PrizesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prizes        []*DynastyPrize        `protobuf:"bytes,1,rep,name=prizes,proto3" json:"prizes,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrizesResponse) Reset() {
	*x = PrizesResponse{}
	mi := &file_dynasty_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrizesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizesResponse) ProtoMessage() {}

func (x *PrizesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizesResponse.ProtoReflect.Descriptor instead.
func (*PrizesResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{24}
}

func (x *PrizesResponse) GetPrizes() []*DynastyPrize {
	if x != nil {
		return x.Prizes
	}
	return nil
}

func (x *PrizesResponse) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetPrizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrizeId       uint64                 `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrizeRequest) Reset() {
	*x = GetPrizeRequest{}
	mi := &file_dynasty_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrizeRequest) ProtoMessage() {}

func (x *GetPrizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrizeRequest.ProtoReflect.Descriptor instead.
func (*GetPrizeRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{25}
}

func (x *GetPrizeRequest) GetPrizeId() uint64 {
	if x != nil {
		return x.PrizeId
	}
	return 0
}

type PrizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prize         *DynastyPrize          `protobuf:"bytes,1,opt,name=prize,proto3" json:"prize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrizeResponse) Reset() {
	*x = PrizeResponse{}
	mi := &file_dynasty_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrizeResponse) ProtoMessage() {}

func (x *PrizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrizeResponse.ProtoReflect.Descriptor instead.
func (*PrizeResponse) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{26}
}

func (x *PrizeResponse) GetPrize() *DynastyPrize {
	if x != nil {
		return x.Prize
	}
	return nil
}

type ClaimPrizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrizeId       uint64                 `protobuf:"varint,1,opt,name=prize_id,json=prizeId,proto3" json:"prize_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPrizeRequest) Reset() {
	*x = ClaimPrizeRequest{}
	mi := &file_dynasty_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPrizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPrizeRequest) ProtoMessage() {}

func (x *ClaimPrizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPrizeRequest.ProtoReflect.Descriptor instead.
func (*ClaimPrizeRequest) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{27}
}

func (x *ClaimPrizeRequest) GetPrizeId() uint64 {
	if x != nil {
		return x.PrizeId
	}
	return 0
}

func (x *ClaimPrizeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DynastyPrize struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Member                     string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	Satisfaction               string                 `protobuf:"bytes,3,opt,name=satisfaction,proto3" json:"satisfaction,omitempty"`
	IntroductionProfitIncrease string                 `protobuf:"bytes,4,opt,name=introduction_profit_increase,json=introductionProfitIncrease,proto3" json:"introduction_profit_increase,omitempty"`
	AccumulatedCapitalReserve  string                 `protobuf:"bytes,5,opt,name=accumulated_capital_reserve,json=accumulatedCapitalReserve,proto3" json:"accumulated_capital_reserve,omitempty"`
	DataStorage                string                 `protobuf:"bytes,6,opt,name=data_storage,json=dataStorage,proto3" json:"data_storage,omitempty"`
	Psc                        int32                  `protobuf:"varint,7,opt,name=psc,proto3" json:"psc,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DynastyPrize) Reset() {
	*x = DynastyPrize{}
	mi := &file_dynasty_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynastyPrize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynastyPrize) ProtoMessage() {}

func (x *DynastyPrize) ProtoReflect() protoreflect.Message {
	mi := &file_dynasty_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynastyPrize.ProtoReflect.Descriptor instead.
func (*DynastyPrize) Descriptor() ([]byte, []int) {
	return file_dynasty_proto_rawDescGZIP(), []int{28}
}

func (x *DynastyPrize) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DynastyPrize) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *DynastyPrize) GetSatisfaction() string {
	if x != nil {
		return x.Satisfaction
	}
	return ""
}

func (x *DynastyPrize) GetIntroductionProfitIncrease() string {
	if x != nil {
		return x.IntroductionProfitIncrease
	}
	return ""
}

func (x *DynastyPrize) GetAccumulatedCapitalReserve() string {
	if x != nil {
		return x.AccumulatedCapitalReserve
	}
	return ""
}

func (x *DynastyPrize) GetDataStorage() string {
	if x != nil {
		return x.DataStorage
	}
	return ""
}

func (x *DynastyPrize) GetPsc() int32 {
	if x != nil {
		return x.Psc
	}
	return 0
}

var File_dynasty_proto protoreflect.FileDescriptor

const file_dynasty_proto_rawDesc = "" +
	"\n" +
	"\rdynasty.proto\x12\adynasty\x1a\fcommon.proto\"N\n" +
	"\x14CreateDynastyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x02 \x01(\x04R\tfeatureId\"2\n" +
	"\x11GetDynastyRequest\x12\x1d\n" +
	"\n" +
	"dynasty_id\x18\x01 \x01(\x04R\tdynastyId\"t\n" +
	"\x1bUpdateDynastyFeatureRequest\x12\x1d\n" +
	"\n" +
	"dynasty_id\x18\x01 \x01(\x04R\tdynastyId\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x02 \x01(\x04R\tfeatureId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\"0\n" +
	"\x15GetUserDynastyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xa5\x02\n" +
	"\x0fDynastyResponse\x12(\n" +
	"\x10user_has_dynasty\x18\x01 \x01(\bR\x0euserHasDynasty\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfamily_id\x18\x03 \x01(\x04R\bfamilyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12#\n" +
	"\rprofile_image\x18\x05 \x01(\tR\fprofileImage\x12@\n" +
	"\x0fdynasty_feature\x18\x06 \x01(\v2\x17.dynasty.DynastyFeatureR\x0edynastyFeature\x125\n" +
	"\bfeatures\x18\a \x03(\v2\x19.dynasty.AvailableFeatureR\bfeatures\"\x80\x02\n" +
	"\x0eDynastyFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rproperties_id\x18\x02 \x01(\tR\fpropertiesId\x12\x12\n" +
	"\x04area\x18\x03 \x01(\tR\x04area\x12\x18\n" +
	"\adensity\x18\x04 \x01(\tR\adensity\x126\n" +
	"\x17feature_profit_increase\x18\x05 \x01(\tR\x15featureProfitIncrease\x120\n" +
	"\x14family_members_count\x18\x06 \x01(\x05R\x12familyMembersCount\x12!\n" +
	"\flast_updated\x18\a \x01(\tR\vlastUpdated\"\x93\x01\n" +
	"\x10AvailableFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rproperties_id\x18\x02 \x01(\tR\fpropertiesId\x12\x18\n" +
	"\adensity\x18\x03 \x01(\tR\adensity\x12\x1c\n" +
	"\tstability\x18\x04 \x01(\tR\tstability\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\"\xd3\x01\n" +
	"\x16SendJoinRequestRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\x12\"\n" +
	"\frelationship\x18\x03 \x01(\tR\frelationship\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\vpermissions\x18\x05 \x01(\v2\x19.dynasty.ChildPermissionsR\vpermissions\"\xc1\x02\n" +
	"\x13JoinRequestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfrom_user\x18\x02 \x01(\x04R\bfromUser\x12\x17\n" +
	"\ato_user\x18\x03 \x01(\x04R\x06toUser\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\"\n" +
	"\frelationship\x18\x05 \x01(\tR\frelationship\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x123\n" +
	"\fto_user_info\x18\a \x01(\v2\x11.common.UserBasicR\n" +
	"toUserInfo\x12:\n" +
	"\rrequest_prize\x18\b \x01(\v2\x15.dynasty.DynastyPrizeR\frequestPrize\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"l\n" +
	"\x16GetSentRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"p\n" +
	"\x1aGetReceivedRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"O\n" +
	"\x15GetJoinRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x88\x01\n" +
	"\x14JoinRequestsResponse\x128\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.dynasty.JoinRequestResponseR\brequests\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\"R\n" +
	"\x18AcceptJoinRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"R\n" +
	"\x18RejectJoinRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"R\n" +
	"\x18DeleteJoinRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"N\n" +
	"\x10GetFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\x12\x1d\n" +
	"\n" +
	"dynasty_id\x18\x02 \x01(\x04R\tdynastyId\"p\n" +
	"\x0eFamilyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"dynasty_id\x18\x02 \x01(\x04R\tdynastyId\x12/\n" +
	"\amembers\x18\x03 \x03(\v2\x15.dynasty.FamilyMemberR\amembers\"q\n" +
	"\x17GetFamilyMembersRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\x80\x01\n" +
	"\x15FamilyMembersResponse\x12/\n" +
	"\amembers\x18\x01 \x03(\v2\x15.dynasty.FamilyMemberR\amembers\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\"\xaa\x01\n" +
	"\fFamilyMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\"\n" +
	"\frelationship\x18\x03 \x01(\tR\frelationship\x12.\n" +
	"\tuser_info\x18\x04 \x01(\v2\x11.common.UserBasicR\buserInfo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xa3\x01\n" +
	"\x1aSetChildPermissionsRequest\x12\"\n" +
	"\rchild_user_id\x18\x01 \x01(\x04R\vchildUserId\x12$\n" +
	"\x0eparent_user_id\x18\x02 \x01(\x04R\fparentUserId\x12;\n" +
	"\vpermissions\x18\x03 \x01(\v2\x19.dynasty.ChildPermissionsR\vpermissions\"\xe0\x01\n" +
	"\x10ChildPermissions\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x10\n" +
	"\x03BFR\x18\x02 \x01(\bR\x03BFR\x12\x0e\n" +
	"\x02SF\x18\x03 \x01(\bR\x02SF\x12\f\n" +
	"\x01W\x18\x04 \x01(\bR\x01W\x12\x0e\n" +
	"\x02JU\x18\x05 \x01(\bR\x02JU\x12\x0e\n" +
	"\x02DM\x18\x06 \x01(\bR\x02DM\x12\x12\n" +
	"\x04PIUP\x18\a \x01(\bR\x04PIUP\x12\x12\n" +
	"\x04PITC\x18\b \x01(\bR\x04PITC\x12\x10\n" +
	"\x03PIC\x18\t \x01(\bR\x03PIC\x12\x12\n" +
	"\x04ESOO\x18\n" +
	" \x01(\bR\x04ESOO\x12\x12\n" +
	"\x04COTB\x18\v \x01(\bR\x04COTB\"f\n" +
	"\x10GetPrizesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"w\n" +
	"\x0ePrizesResponse\x12-\n" +
	"\x06prizes\x18\x01 \x03(\v2\x15.dynasty.DynastyPrizeR\x06prizes\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationMetaR\n" +
	"pagination\",\n" +
	"\x0fGetPrizeRequest\x12\x19\n" +
	"\bprize_id\x18\x01 \x01(\x04R\aprizeId\"<\n" +
	"\rPrizeResponse\x12+\n" +
	"\x05prize\x18\x01 \x01(\v2\x15.dynasty.DynastyPrizeR\x05prize\"G\n" +
	"\x11ClaimPrizeRequest\x12\x19\n" +
	"\bprize_id\x18\x01 \x01(\x04R\aprizeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x91\x02\n" +
	"\fDynastyPrize\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\x12\"\n" +
	"\fsatisfaction\x18\x03 \x01(\tR\fsatisfaction\x12@\n" +
	"\x1cintroduction_profit_increase\x18\x04 \x01(\tR\x1aintroductionProfitIncrease\x12>\n" +
	"\x1baccumulated_capital_reserve\x18\x05 \x01(\tR\x19accumulatedCapitalReserve\x12!\n" +
	"\fdata_storage\x18\x06 \x01(\tR\vdataStorage\x12\x10\n" +
	"\x03psc\x18\a \x01(\x05R\x03psc2\xc2\x02\n" +
	"\x0eDynastyService\x12H\n" +
	"\rCreateDynasty\x12\x1d.dynasty.CreateDynastyRequest\x1a\x18.dynasty.DynastyResponse\x12B\n" +
	"\n" +
	"GetDynasty\x12\x1a.dynasty.GetDynastyRequest\x1a\x18.dynasty.DynastyResponse\x12V\n" +
	"\x14UpdateDynastyFeature\x12$.dynasty.UpdateDynastyFeatureRequest\x1a\x18.dynasty.DynastyResponse\x12J\n" +
	"\x0eGetUserDynasty\x12\x1e.dynasty.GetUserDynastyRequest\x1a\x18.dynasty.DynastyResponse2\xb9\x04\n" +
	"\x12JoinRequestService\x12P\n" +
	"\x0fSendJoinRequest\x12\x1f.dynasty.SendJoinRequestRequest\x1a\x1c.dynasty.JoinRequestResponse\x12Q\n" +
	"\x0fGetSentRequests\x12\x1f.dynasty.GetSentRequestsRequest\x1a\x1d.dynasty.JoinRequestsResponse\x12Y\n" +
	"\x13GetReceivedRequests\x12#.dynasty.GetReceivedRequestsRequest\x1a\x1d.dynasty.JoinRequestsResponse\x12N\n" +
	"\x0eGetJoinRequest\x12\x1e.dynasty.GetJoinRequestRequest\x1a\x1c.dynasty.JoinRequestResponse\x12E\n" +
	"\x11AcceptJoinRequest\x12!.dynasty.AcceptJoinRequestRequest\x1a\r.common.Empty\x12E\n" +
	"\x11RejectJoinRequest\x12!.dynasty.RejectJoinRequestRequest\x1a\r.common.Empty\x12E\n" +
	"\x11DeleteJoinRequest\x12!.dynasty.DeleteJoinRequestRequest\x1a\r.common.Empty2\xf1\x01\n" +
	"\rFamilyService\x12?\n" +
	"\tGetFamily\x12\x19.dynasty.GetFamilyRequest\x1a\x17.dynasty.FamilyResponse\x12T\n" +
	"\x10GetFamilyMembers\x12 .dynasty.GetFamilyMembersRequest\x1a\x1e.dynasty.FamilyMembersResponse\x12I\n" +
	"\x13SetChildPermissions\x12#.dynasty.SetChildPermissionsRequest\x1a\r.common.Empty2\xcd\x01\n" +
	"\x13DynastyPrizeService\x12?\n" +
	"\tGetPrizes\x12\x19.dynasty.GetPrizesRequest\x1a\x17.dynasty.PrizesResponse\x12<\n" +
	"\bGetPrize\x12\x18.dynasty.GetPrizeRequest\x1a\x16.dynasty.PrizeResponse\x127\n" +
	"\n" +
	"ClaimPrize\x12\x1a.dynasty.ClaimPrizeRequest\x1a\r.common.EmptyB\x1bZ\x19metargb/shared/pb/dynastyb\x06proto3"

var (
	file_dynasty_proto_rawDescOnce sync.Once
	file_dynasty_proto_rawDescData []byte
)

func file_dynasty_proto_rawDescGZIP() []byte {
	file_dynasty_proto_rawDescOnce.Do(func() {
		file_dynasty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynasty_proto_rawDesc), len(file_dynasty_proto_rawDesc)))
	})
	return file_dynasty_proto_rawDescData
}

var file_dynasty_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_dynasty_proto_goTypes = []any{
	(*CreateDynastyRequest)(nil),        // 0: dynasty.CreateDynastyRequest
	(*GetDynastyRequest)(nil),           // 1: dynasty.GetDynastyRequest
	(*UpdateDynastyFeatureRequest)(nil), // 2: dynasty.UpdateDynastyFeatureRequest
	(*GetUserDynastyRequest)(nil),       // 3: dynasty.GetUserDynastyRequest
	(*DynastyResponse)(nil),             // 4: dynasty.DynastyResponse
	(*DynastyFeature)(nil),              // 5: dynasty.DynastyFeature
	(*AvailableFeature)(nil),            // 6: dynasty.AvailableFeature
	(*SendJoinRequestRequest)(nil),      // 7: dynasty.SendJoinRequestRequest
	(*JoinRequestResponse)(nil),         // 8: dynasty.JoinRequestResponse
	(*GetSentRequestsRequest)(nil),      // 9: dynasty.GetSentRequestsRequest
	(*GetReceivedRequestsRequest)(nil),  // 10: dynasty.GetReceivedRequestsRequest
	(*GetJoinRequestRequest)(nil),       // 11: dynasty.GetJoinRequestRequest
	(*JoinRequestsResponse)(nil),        // 12: dynasty.JoinRequestsResponse
	(*AcceptJoinRequestRequest)(nil),    // 13: dynasty.AcceptJoinRequestRequest
	(*RejectJoinRequestRequest)(nil),    // 14: dynasty.RejectJoinRequestRequest
	(*DeleteJoinRequestRequest)(nil),    // 15: dynasty.DeleteJoinRequestRequest
	(*GetFamilyRequest)(nil),            // 16: dynasty.GetFamilyRequest
	(*FamilyResponse)(nil),              // 17: dynasty.FamilyResponse
	(*GetFamilyMembersRequest)(nil),     // 18: dynasty.GetFamilyMembersRequest
	(*FamilyMembersResponse)(nil),       // 19: dynasty.FamilyMembersResponse
	(*FamilyMember)(nil),                // 20: dynasty.FamilyMember
	(*SetChildPermissionsRequest)(nil),  // 21: dynasty.SetChildPermissionsRequest
	(*ChildPermissions)(nil),            // 22: dynasty.ChildPermissions
	(*GetPrizesRequest)(nil),            // 23: dynasty.GetPrizesRequest
	(*PrizesResponse)(nil),              // 24: dynasty.PrizesResponse
	(*GetPrizeRequest)(nil),             // 25: dynasty.GetPrizeRequest
	(*PrizeResponse)(nil),               // 26: dynasty.PrizeResponse
	(*ClaimPrizeRequest)(nil),           // 27: dynasty.ClaimPrizeRequest
	(*DynastyPrize)(nil),                // 28: dynasty.DynastyPrize
	(*common.UserBasic)(nil),            // 29: common.UserBasic
	(*common.PaginationRequest)(nil),    // 30: common.PaginationRequest
	(*common.PaginationMeta)(nil),       // 31: common.PaginationMeta
	(*common.Empty)(nil),                // 32: common.Empty
}
var file_dynasty_proto_depIdxs = []int32{
	5,  // 0: dynasty.DynastyResponse.dynasty_feature:type_name -> dynasty.DynastyFeature
	6,  // 1: dynasty.DynastyResponse.features:type_name -> dynasty.AvailableFeature
	22, // 2: dynasty.SendJoinRequestRequest.permissions:type_name -> dynasty.ChildPermissions
	29, // 3: dynasty.JoinRequestResponse.to_user_info:type_name -> common.UserBasic
	28, // 4: dynasty.JoinRequestResponse.request_prize:type_name -> dynasty.DynastyPrize
	30, // 5: dynasty.GetSentRequestsRequest.pagination:type_name -> common.PaginationRequest
	30, // 6: dynasty.GetReceivedRequestsRequest.pagination:type_name -> common.PaginationRequest
	8,  // 7: dynasty.JoinRequestsResponse.requests:type_name -> dynasty.JoinRequestResponse
	31, // 8: dynasty.JoinRequestsResponse.pagination:type_name -> common.PaginationMeta
	20, // 9: dynasty.FamilyResponse.members:type_name -> dynasty.FamilyMember
	30, // 10: dynasty.GetFamilyMembersRequest.pagination:type_name -> common.PaginationRequest
	20, // 11: dynasty.FamilyMembersResponse.members:type_name -> dynasty.FamilyMember
	31, // 12: dynasty.FamilyMembersResponse.pagination:type_name -> common.PaginationMeta
	29, // 13: dynasty.FamilyMember.user_info:type_name -> common.UserBasic
	22, // 14: dynasty.SetChildPermissionsRequest.permissions:type_name -> dynasty.ChildPermissions
	30, // 15: dynasty.GetPrizesRequest.pagination:type_name -> common.PaginationRequest
	28, // 16: dynasty.PrizesResponse.prizes:type_name -> dynasty.DynastyPrize
	31, // 17: dynasty.PrizesResponse.pagination:type_name -> common.PaginationMeta
	28, // 18: dynasty.PrizeResponse.prize:type_name -> dynasty.DynastyPrize
	0,  // 19: dynasty.DynastyService.CreateDynasty:input_type -> dynasty.CreateDynastyRequest
	1,  // 20: dynasty.DynastyService.GetDynasty:input_type -> dynasty.GetDynastyRequest
	2,  // 21: dynasty.DynastyService.UpdateDynastyFeature:input_type -> dynasty.UpdateDynastyFeatureRequest
	3,  // 22: dynasty.DynastyService.GetUserDynasty:input_type -> dynasty.GetUserDynastyRequest
	7,  // 23: dynasty.JoinRequestService.SendJoinRequest:input_type -> dynasty.SendJoinRequestRequest
	9,  // 24: dynasty.JoinRequestService.GetSentRequests:input_type -> dynasty.GetSentRequestsRequest
	10, // 25: dynasty.JoinRequestService.GetReceivedRequests:input_type -> dynasty.GetReceivedRequestsRequest
	11, // 26: dynasty.JoinRequestService.GetJoinRequest:input_type -> dynasty.GetJoinRequestRequest
	13, // 27: dynasty.JoinRequestService.AcceptJoinRequest:input_type -> dynasty.AcceptJoinRequestRequest
	14, // 28: dynasty.JoinRequestService.RejectJoinRequest:input_type -> dynasty.RejectJoinRequestRequest
	15, // 29: dynasty.JoinRequestService.DeleteJoinRequest:input_type -> dynasty.DeleteJoinRequestRequest
	16, // 30: dynasty.FamilyService.GetFamily:input_type -> dynasty.GetFamilyRequest
	18, // 31: dynasty.FamilyService.GetFamilyMembers:input_type -> dynasty.GetFamilyMembersRequest
	21, // 32: dynasty.FamilyService.SetChildPermissions:input_type -> dynasty.SetChildPermissionsRequest
	23, // 33: dynasty.DynastyPrizeService.GetPrizes:input_type -> dynasty.GetPrizesRequest
	25, // 34: dynasty.DynastyPrizeService.GetPrize:input_type -> dynasty.GetPrizeRequest
	27, // 35: dynasty.DynastyPrizeService.ClaimPrize:input_type -> dynasty.ClaimPrizeRequest
	4,  // 36: dynasty.DynastyService.CreateDynasty:output_type -> dynasty.DynastyResponse
	4,  // 37: dynasty.DynastyService.GetDynasty:output_type -> dynasty.DynastyResponse
	4,  // 38: dynasty.DynastyService.UpdateDynastyFeature:output_type -> dynasty.DynastyResponse
	4,  // 39: dynasty.DynastyService.GetUserDynasty:output_type -> dynasty.DynastyResponse
	8,  // 40: dynasty.JoinRequestService.SendJoinRequest:output_type -> dynasty.JoinRequestResponse
	12, // 41: dynasty.JoinRequestService.GetSentRequests:output_type -> dynasty.JoinRequestsResponse
	12, // 42: dynasty.JoinRequestService.GetReceivedRequests:output_type -> dynasty.JoinRequestsResponse
	8,  // 43: dynasty.JoinRequestService.GetJoinRequest:output_type -> dynasty.JoinRequestResponse
	32, // 44: dynasty.JoinRequestService.AcceptJoinRequest:output_type -> common.Empty
	32, // 45: dynasty.JoinRequestService.RejectJoinRequest:output_type -> common.Empty
	32, // 46: dynasty.JoinRequestService.DeleteJoinRequest:output_type -> common.Empty
	17, // 47: dynasty.FamilyService.GetFamily:output_type -> dynasty.FamilyResponse
	19, // 48: dynasty.FamilyService.GetFamilyMembers:output_type -> dynasty.FamilyMembersResponse
	32, // 49: dynasty.FamilyService.SetChildPermissions:output_type -> common.Empty
	24, // 50: dynasty.DynastyPrizeService.GetPrizes:output_type -> dynasty.PrizesResponse
	26, // 51: dynasty.DynastyPrizeService.GetPrize:output_type -> dynasty.PrizeResponse
	32, // 52: dynasty.DynastyPrizeService.ClaimPrize:output_type -> common.Empty
	36, // [36:53] is the sub-list for method output_type
	19, // [19:36] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_dynasty_proto_init() }
func file_dynasty_proto_init() {
	if File_dynasty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynasty_proto_rawDesc), len(file_dynasty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_dynasty_proto_goTypes,
		DependencyIndexes: file_dynasty_proto_depIdxs,
		MessageInfos:      file_dynasty_proto_msgTypes,
	}.Build()
	File_dynasty_proto = out.File
	file_dynasty_proto_goTypes = nil
	file_dynasty_proto_depIdxs = nil
}
