// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Code            string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	ReferrerId      uint64                 `protobuf:"varint,6,opt,name=referrer_id,json=referrerId,proto3" json:"referrer_id,omitempty"`
	Score           int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EmailVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	PhoneVerifiedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=phone_verified_at,json=phoneVerifiedAt,proto3" json:"phone_verified_at,omitempty"`
	AccessToken     string                 `protobuf:"bytes,12,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,13,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType       string                 `protobuf:"bytes,14,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn       int64                  `protobuf:"varint,15,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Ip              string                 `protobuf:"bytes,16,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *User) GetReferrerId() uint64 {
	if x != nil {
		return x.ReferrerId
	}
	return 0
}

func (x *User) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *User) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetEmailVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return nil
}

func (x *User) GetPhoneVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PhoneVerifiedAt
	}
	return nil
}

func (x *User) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *User) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *User) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *User) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *User) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type KYC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Fname         string                 `protobuf:"bytes,3,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname         string                 `protobuf:"bytes,4,opt,name=lname,proto3" json:"lname,omitempty"`
	FullName      string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Birthdate     string                 `protobuf:"bytes,7,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	NationalCode  string                 `protobuf:"bytes,8,opt,name=national_code,json=nationalCode,proto3" json:"national_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KYC) Reset() {
	*x = KYC{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYC) ProtoMessage() {}

func (x *KYC) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYC.ProtoReflect.Descriptor instead.
func (*KYC) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *KYC) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KYC) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KYC) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *KYC) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *KYC) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *KYC) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *KYC) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *KYC) GetNationalCode() string {
	if x != nil {
		return x.NationalCode
	}
	return ""
}

func (x *KYC) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KYC) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Settings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AutomaticLogout int32                  `protobuf:"varint,3,opt,name=automatic_logout,json=automaticLogout,proto3" json:"automatic_logout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Settings) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Settings) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Settings) GetAutomaticLogout() int32 {
	if x != nil {
		return x.AutomaticLogout
	}
	return 0
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ImageableType string                 `protobuf:"bytes,3,opt,name=imageable_type,json=imageableType,proto3" json:"imageable_type,omitempty"`
	ImageableId   uint64                 `protobuf:"varint,4,opt,name=imageable_id,json=imageableId,proto3" json:"imageable_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetImageableType() string {
	if x != nil {
		return x.ImageableType
	}
	return ""
}

func (x *Image) GetImageableId() uint64 {
	if x != nil {
		return x.ImageableId
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

type Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Level) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Level) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Level) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Level) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackUrl       string                 `protobuf:"bytes,1,opt,name=back_url,json=backUrl,proto3" json:"back_url,omitempty"`
	Referral      string                 `protobuf:"bytes,2,opt,name=referral,proto3" json:"referral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetBackUrl() string {
	if x != nil {
		return x.BackUrl
	}
	return ""
}

func (x *RegisterRequest) GetReferral() string {
	if x != nil {
		return x.Referral
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectTo    string                 `protobuf:"bytes,1,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	BackUrl       string                 `protobuf:"bytes,2,opt,name=back_url,json=backUrl,proto3" json:"back_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RedirectRequest) GetRedirectTo() string {
	if x != nil {
		return x.RedirectTo
	}
	return ""
}

func (x *RedirectRequest) GetBackUrl() string {
	if x != nil {
		return x.BackUrl
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RedirectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *CallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int32                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *CallbackResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CallbackResponse) GetExpiresAt() int32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CallbackResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetMeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token           string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	AccessToken     string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AutomaticLogout int32                  `protobuf:"varint,5,opt,name=automatic_logout,json=automaticLogout,proto3" json:"automatic_logout,omitempty"`
	Code            string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Level           *Level                 `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	Image           string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Notifications   int32                  `protobuf:"varint,9,opt,name=notifications,proto3" json:"notifications,omitempty"`
	// CRITICAL: Preserve Laravel typos for API compatibility!
	// Laravel has "socre" not "score" and "unasnwered" not "unanswered"
	SocrePercentageToNextLevel float64 `protobuf:"fixed64,10,opt,name=socre_percentage_to_next_level,json=socrePercentageToNextLevel,proto3" json:"socre_percentage_to_next_level,omitempty"`
	UnasnweredQuestionsCount   int32   `protobuf:"varint,11,opt,name=unasnwered_questions_count,json=unasnweredQuestionsCount,proto3" json:"unasnwered_questions_count,omitempty"`
	HourlyProfitTimePercentage float64 `protobuf:"fixed64,12,opt,name=hourly_profit_time_percentage,json=hourlyProfitTimePercentage,proto3" json:"hourly_profit_time_percentage,omitempty"`
	VerifiedKyc                bool    `protobuf:"varint,13,opt,name=verified_kyc,json=verifiedKyc,proto3" json:"verified_kyc,omitempty"`
	Birthdate                  string  `protobuf:"bytes,14,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *UserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserResponse) GetAutomaticLogout() int32 {
	if x != nil {
		return x.AutomaticLogout
	}
	return 0
}

func (x *UserResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserResponse) GetLevel() *Level {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *UserResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UserResponse) GetNotifications() int32 {
	if x != nil {
		return x.Notifications
	}
	return 0
}

func (x *UserResponse) GetSocrePercentageToNextLevel() float64 {
	if x != nil {
		return x.SocrePercentageToNextLevel
	}
	return 0
}

func (x *UserResponse) GetUnasnweredQuestionsCount() int32 {
	if x != nil {
		return x.UnasnweredQuestionsCount
	}
	return 0
}

func (x *UserResponse) GetHourlyProfitTimePercentage() float64 {
	if x != nil {
		return x.HourlyProfitTimePercentage
	}
	return 0
}

func (x *UserResponse) GetVerifiedKyc() bool {
	if x != nil {
		return x.VerifiedKyc
	}
	return false
}

func (x *UserResponse) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RequestAccountSecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimeMinutes   int32                  `protobuf:"varint,2,opt,name=time_minutes,json=timeMinutes,proto3" json:"time_minutes,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountSecurityRequest) Reset() {
	*x = RequestAccountSecurityRequest{}
	mi := &file_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountSecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountSecurityRequest) ProtoMessage() {}

func (x *RequestAccountSecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountSecurityRequest.ProtoReflect.Descriptor instead.
func (*RequestAccountSecurityRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{17}
}

func (x *RequestAccountSecurityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RequestAccountSecurityRequest) GetTimeMinutes() int32 {
	if x != nil {
		return x.TimeMinutes
	}
	return 0
}

func (x *RequestAccountSecurityRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type VerifyAccountSecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccountSecurityRequest) Reset() {
	*x = VerifyAccountSecurityRequest{}
	mi := &file_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccountSecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccountSecurityRequest) ProtoMessage() {}

func (x *VerifyAccountSecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccountSecurityRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccountSecurityRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyAccountSecurityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyAccountSecurityRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyAccountSecurityRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VerifyAccountSecurityRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetUserWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWalletRequest) Reset() {
	*x = GetUserWalletRequest{}
	mi := &file_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWalletRequest) ProtoMessage() {}

func (x *GetUserWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWalletRequest.ProtoReflect.Descriptor instead.
func (*GetUserWalletRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserWalletRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psc           string                 `protobuf:"bytes,1,opt,name=psc,proto3" json:"psc,omitempty"`
	Irr           string                 `protobuf:"bytes,2,opt,name=irr,proto3" json:"irr,omitempty"`
	Red           string                 `protobuf:"bytes,3,opt,name=red,proto3" json:"red,omitempty"`
	Blue          string                 `protobuf:"bytes,4,opt,name=blue,proto3" json:"blue,omitempty"`
	Yellow        string                 `protobuf:"bytes,5,opt,name=yellow,proto3" json:"yellow,omitempty"`
	Satisfaction  string                 `protobuf:"bytes,6,opt,name=satisfaction,proto3" json:"satisfaction,omitempty"`
	Effect        float64                `protobuf:"fixed64,7,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserWalletResponse) Reset() {
	*x = UserWalletResponse{}
	mi := &file_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWalletResponse) ProtoMessage() {}

func (x *UserWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWalletResponse.ProtoReflect.Descriptor instead.
func (*UserWalletResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{22}
}

func (x *UserWalletResponse) GetPsc() string {
	if x != nil {
		return x.Psc
	}
	return ""
}

func (x *UserWalletResponse) GetIrr() string {
	if x != nil {
		return x.Irr
	}
	return ""
}

func (x *UserWalletResponse) GetRed() string {
	if x != nil {
		return x.Red
	}
	return ""
}

func (x *UserWalletResponse) GetBlue() string {
	if x != nil {
		return x.Blue
	}
	return ""
}

func (x *UserWalletResponse) GetYellow() string {
	if x != nil {
		return x.Yellow
	}
	return ""
}

func (x *UserWalletResponse) GetSatisfaction() string {
	if x != nil {
		return x.Satisfaction
	}
	return ""
}

func (x *UserWalletResponse) GetEffect() float64 {
	if x != nil {
		return x.Effect
	}
	return 0
}

type GetUserLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLevelRequest) Reset() {
	*x = GetUserLevelRequest{}
	mi := &file_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLevelRequest) ProtoMessage() {}

func (x *GetUserLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLevelRequest.ProtoReflect.Descriptor instead.
func (*GetUserLevelRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserLevelRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserLevelResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Level            *Level                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Score            int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	PercentageToNext float64                `protobuf:"fixed64,3,opt,name=percentage_to_next,json=percentageToNext,proto3" json:"percentage_to_next,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserLevelResponse) Reset() {
	*x = UserLevelResponse{}
	mi := &file_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLevelResponse) ProtoMessage() {}

func (x *UserLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLevelResponse.ProtoReflect.Descriptor instead.
func (*UserLevelResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{24}
}

func (x *UserLevelResponse) GetLevel() *Level {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *UserLevelResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserLevelResponse) GetPercentageToNext() float64 {
	if x != nil {
		return x.PercentageToNext
	}
	return 0
}

type SubmitKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Fname         string                 `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname         string                 `protobuf:"bytes,3,opt,name=lname,proto3" json:"lname,omitempty"`
	NationalCode  string                 `protobuf:"bytes,4,opt,name=national_code,json=nationalCode,proto3" json:"national_code,omitempty"`
	Birthdate     string                 `protobuf:"bytes,5,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitKYCRequest) Reset() {
	*x = SubmitKYCRequest{}
	mi := &file_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitKYCRequest) ProtoMessage() {}

func (x *SubmitKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitKYCRequest.ProtoReflect.Descriptor instead.
func (*SubmitKYCRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{25}
}

func (x *SubmitKYCRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitKYCRequest) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *SubmitKYCRequest) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *SubmitKYCRequest) GetNationalCode() string {
	if x != nil {
		return x.NationalCode
	}
	return ""
}

func (x *SubmitKYCRequest) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

type KYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Fname         string                 `protobuf:"bytes,3,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname         string                 `protobuf:"bytes,4,opt,name=lname,proto3" json:"lname,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Birthdate     string                 `protobuf:"bytes,6,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KYCResponse) Reset() {
	*x = KYCResponse{}
	mi := &file_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCResponse) ProtoMessage() {}

func (x *KYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCResponse.ProtoReflect.Descriptor instead.
func (*KYCResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{26}
}

func (x *KYCResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KYCResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KYCResponse) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *KYCResponse) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *KYCResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *KYCResponse) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

type GetKYCStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCStatusRequest) Reset() {
	*x = GetKYCStatusRequest{}
	mi := &file_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCStatusRequest) ProtoMessage() {}

func (x *GetKYCStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKYCStatusRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{27}
}

func (x *GetKYCStatusRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type VerifyBankAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BankName      string                 `protobuf:"bytes,2,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	ShabaNum      string                 `protobuf:"bytes,3,opt,name=shaba_num,json=shabaNum,proto3" json:"shaba_num,omitempty"`
	CardNum       string                 `protobuf:"bytes,4,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBankAccountRequest) Reset() {
	*x = VerifyBankAccountRequest{}
	mi := &file_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBankAccountRequest) ProtoMessage() {}

func (x *VerifyBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBankAccountRequest.ProtoReflect.Descriptor instead.
func (*VerifyBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{28}
}

func (x *VerifyBankAccountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyBankAccountRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *VerifyBankAccountRequest) GetShabaNum() string {
	if x != nil {
		return x.ShabaNum
	}
	return ""
}

func (x *VerifyBankAccountRequest) GetCardNum() string {
	if x != nil {
		return x.CardNum
	}
	return ""
}

type BankAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BankName      string                 `protobuf:"bytes,2,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	ShabaNum      string                 `protobuf:"bytes,3,opt,name=shaba_num,json=shabaNum,proto3" json:"shaba_num,omitempty"`
	CardNum       string                 `protobuf:"bytes,4,opt,name=card_num,json=cardNum,proto3" json:"card_num,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Errors        string                 `protobuf:"bytes,6,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccountResponse) Reset() {
	*x = BankAccountResponse{}
	mi := &file_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountResponse) ProtoMessage() {}

func (x *BankAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountResponse.ProtoReflect.Descriptor instead.
func (*BankAccountResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{29}
}

func (x *BankAccountResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankAccountResponse) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankAccountResponse) GetShabaNum() string {
	if x != nil {
		return x.ShabaNum
	}
	return ""
}

func (x *BankAccountResponse) GetCardNum() string {
	if x != nil {
		return x.CardNum
	}
	return ""
}

func (x *BankAccountResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BankAccountResponse) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbb\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1f\n" +
	"\vreferrer_id\x18\x06 \x01(\x04R\n" +
	"referrerId\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12F\n" +
	"\x11email_verified_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0femailVerifiedAt\x12F\n" +
	"\x11phone_verified_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0fphoneVerifiedAt\x12!\n" +
	"\faccess_token\x18\f \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\r \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x0e \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x0f \x01(\x03R\texpiresIn\x12\x0e\n" +
	"\x02ip\x18\x10 \x01(\tR\x02ip\"\xc8\x02\n" +
	"\x03KYC\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05fname\x18\x03 \x01(\tR\x05fname\x12\x14\n" +
	"\x05lname\x18\x04 \x01(\tR\x05lname\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1c\n" +
	"\tbirthdate\x18\a \x01(\tR\tbirthdate\x12#\n" +
	"\rnational_code\x18\b \x01(\tR\fnationalCode\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\bSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12)\n" +
	"\x10automatic_logout\x18\x03 \x01(\x05R\x0fautomaticLogout\"s\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12%\n" +
	"\x0eimageable_type\x18\x03 \x01(\tR\rimageableType\x12!\n" +
	"\fimageable_id\x18\x04 \x01(\x04R\vimageableId\"\xb6\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aread_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\"e\n" +
	"\x05Level\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"H\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bback_url\x18\x01 \x01(\tR\abackUrl\x12\x1a\n" +
	"\breferral\x18\x02 \x01(\tR\breferral\"$\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"M\n" +
	"\x0fRedirectRequest\x12\x1f\n" +
	"\vredirect_to\x18\x01 \x01(\tR\n" +
	"redirectTo\x12\x19\n" +
	"\bback_url\x18\x02 \x01(\tR\abackUrl\"$\n" +
	"\x10RedirectResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\";\n" +
	"\x0fCallbackRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"j\n" +
	"\x10CallbackResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x05R\texpiresAt\x12!\n" +
	"\fredirect_url\x18\x03 \x01(\tR\vredirectUrl\"$\n" +
	"\fGetMeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x8f\x04\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12)\n" +
	"\x10automatic_logout\x18\x05 \x01(\x05R\x0fautomaticLogout\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12!\n" +
	"\x05level\x18\a \x01(\v2\v.auth.LevelR\x05level\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12$\n" +
	"\rnotifications\x18\t \x01(\x05R\rnotifications\x12B\n" +
	"\x1esocre_percentage_to_next_level\x18\n" +
	" \x01(\x01R\x1asocrePercentageToNextLevel\x12<\n" +
	"\x1aunasnwered_questions_count\x18\v \x01(\x05R\x18unasnweredQuestionsCount\x12A\n" +
	"\x1dhourly_profit_time_percentage\x18\f \x01(\x01R\x1ahourlyProfitTimePercentage\x12!\n" +
	"\fverified_kyc\x18\r \x01(\bR\vverifiedKyc\x12\x1c\n" +
	"\tbirthdate\x18\x0e \x01(\tR\tbirthdate\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\\\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"q\n" +
	"\x1dRequestAccountSecurityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\ftime_minutes\x18\x02 \x01(\x05R\vtimeMinutes\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"z\n" +
	"\x1cVerifyAccountSecurityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"o\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"/\n" +
	"\x14GetUserWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\xb2\x01\n" +
	"\x12UserWalletResponse\x12\x10\n" +
	"\x03psc\x18\x01 \x01(\tR\x03psc\x12\x10\n" +
	"\x03irr\x18\x02 \x01(\tR\x03irr\x12\x10\n" +
	"\x03red\x18\x03 \x01(\tR\x03red\x12\x12\n" +
	"\x04blue\x18\x04 \x01(\tR\x04blue\x12\x16\n" +
	"\x06yellow\x18\x05 \x01(\tR\x06yellow\x12\"\n" +
	"\fsatisfaction\x18\x06 \x01(\tR\fsatisfaction\x12\x16\n" +
	"\x06effect\x18\a \x01(\x01R\x06effect\".\n" +
	"\x13GetUserLevelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"z\n" +
	"\x11UserLevelResponse\x12!\n" +
	"\x05level\x18\x01 \x01(\v2\v.auth.LevelR\x05level\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12,\n" +
	"\x12percentage_to_next\x18\x03 \x01(\x01R\x10percentageToNext\"\x9a\x01\n" +
	"\x10SubmitKYCRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05fname\x18\x02 \x01(\tR\x05fname\x12\x14\n" +
	"\x05lname\x18\x03 \x01(\tR\x05lname\x12#\n" +
	"\rnational_code\x18\x04 \x01(\tR\fnationalCode\x12\x1c\n" +
	"\tbirthdate\x18\x05 \x01(\tR\tbirthdate\"\x98\x01\n" +
	"\vKYCResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05fname\x18\x03 \x01(\tR\x05fname\x12\x14\n" +
	"\x05lname\x18\x04 \x01(\tR\x05lname\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1c\n" +
	"\tbirthdate\x18\x06 \x01(\tR\tbirthdate\".\n" +
	"\x13GetKYCStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x88\x01\n" +
	"\x18VerifyBankAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tbank_name\x18\x02 \x01(\tR\bbankName\x12\x1b\n" +
	"\tshaba_num\x18\x03 \x01(\tR\bshabaNum\x12\x19\n" +
	"\bcard_num\x18\x04 \x01(\tR\acardNum\"\xaa\x01\n" +
	"\x13BankAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tbank_name\x18\x02 \x01(\tR\bbankName\x12\x1b\n" +
	"\tshaba_num\x18\x03 \x01(\tR\bshabaNum\x12\x19\n" +
	"\bcard_num\x18\x04 \x01(\tR\acardNum\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x16\n" +
	"\x06errors\x18\x06 \x01(\tR\x06errors2\x9c\x04\n" +
	"\vAuthService\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x129\n" +
	"\bRedirect\x12\x15.auth.RedirectRequest\x1a\x16.auth.RedirectResponse\x129\n" +
	"\bCallback\x12\x15.auth.CallbackRequest\x1a\x16.auth.CallbackResponse\x12/\n" +
	"\x05GetMe\x12\x12.auth.GetMeRequest\x1a\x12.auth.UserResponse\x125\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12U\n" +
	"\x16RequestAccountSecurity\x12#.auth.RequestAccountSecurityRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x15VerifyAccountSecurity\x12\".auth.VerifyAccountSecurityRequest\x1a\x16.google.protobuf.Empty2\xfe\x01\n" +
	"\vUserService\x12+\n" +
	"\aGetUser\x12\x14.auth.GetUserRequest\x1a\n" +
	".auth.User\x127\n" +
	"\rUpdateProfile\x12\x1a.auth.UpdateProfileRequest\x1a\n" +
	".auth.User\x12E\n" +
	"\rGetUserWallet\x12\x1a.auth.GetUserWalletRequest\x1a\x18.auth.UserWalletResponse\x12B\n" +
	"\fGetUserLevel\x12\x19.auth.GetUserLevelRequest\x1a\x17.auth.UserLevelResponse2\xd2\x01\n" +
	"\n" +
	"KYCService\x126\n" +
	"\tSubmitKYC\x12\x16.auth.SubmitKYCRequest\x1a\x11.auth.KYCResponse\x12<\n" +
	"\fGetKYCStatus\x12\x19.auth.GetKYCStatusRequest\x1a\x11.auth.KYCResponse\x12N\n" +
	"\x11VerifyBankAccount\x12\x1e.auth.VerifyBankAccountRequest\x1a\x19.auth.BankAccountResponseB\x18Z\x16metargb/shared/pb/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_auth_proto_goTypes = []any{
	(*User)(nil),                          // 0: auth.User
	(*KYC)(nil),                           // 1: auth.KYC
	(*Settings)(nil),                      // 2: auth.Settings
	(*Image)(nil),                         // 3: auth.Image
	(*Notification)(nil),                  // 4: auth.Notification
	(*Level)(nil),                         // 5: auth.Level
	(*RegisterRequest)(nil),               // 6: auth.RegisterRequest
	(*RegisterResponse)(nil),              // 7: auth.RegisterResponse
	(*RedirectRequest)(nil),               // 8: auth.RedirectRequest
	(*RedirectResponse)(nil),              // 9: auth.RedirectResponse
	(*CallbackRequest)(nil),               // 10: auth.CallbackRequest
	(*CallbackResponse)(nil),              // 11: auth.CallbackResponse
	(*GetMeRequest)(nil),                  // 12: auth.GetMeRequest
	(*UserResponse)(nil),                  // 13: auth.UserResponse
	(*LogoutRequest)(nil),                 // 14: auth.LogoutRequest
	(*ValidateTokenRequest)(nil),          // 15: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),         // 16: auth.ValidateTokenResponse
	(*RequestAccountSecurityRequest)(nil), // 17: auth.RequestAccountSecurityRequest
	(*VerifyAccountSecurityRequest)(nil),  // 18: auth.VerifyAccountSecurityRequest
	(*GetUserRequest)(nil),                // 19: auth.GetUserRequest
	(*UpdateProfileRequest)(nil),          // 20: auth.UpdateProfileRequest
	(*GetUserWalletRequest)(nil),          // 21: auth.GetUserWalletRequest
	(*UserWalletResponse)(nil),            // 22: auth.UserWalletResponse
	(*GetUserLevelRequest)(nil),           // 23: auth.GetUserLevelRequest
	(*UserLevelResponse)(nil),             // 24: auth.UserLevelResponse
	(*SubmitKYCRequest)(nil),              // 25: auth.SubmitKYCRequest
	(*KYCResponse)(nil),                   // 26: auth.KYCResponse
	(*GetKYCStatusRequest)(nil),           // 27: auth.GetKYCStatusRequest
	(*VerifyBankAccountRequest)(nil),      // 28: auth.VerifyBankAccountRequest
	(*BankAccountResponse)(nil),           // 29: auth.BankAccountResponse
	(*timestamppb.Timestamp)(nil),         // 30: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 31: google.protobuf.Empty
}
var file_auth_proto_depIdxs = []int32{
	30, // 0: auth.User.last_seen:type_name -> google.protobuf.Timestamp
	30, // 1: auth.User.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: auth.User.email_verified_at:type_name -> google.protobuf.Timestamp
	30, // 3: auth.User.phone_verified_at:type_name -> google.protobuf.Timestamp
	30, // 4: auth.KYC.created_at:type_name -> google.protobuf.Timestamp
	30, // 5: auth.KYC.updated_at:type_name -> google.protobuf.Timestamp
	30, // 6: auth.Notification.created_at:type_name -> google.protobuf.Timestamp
	30, // 7: auth.Notification.read_at:type_name -> google.protobuf.Timestamp
	5,  // 8: auth.UserResponse.level:type_name -> auth.Level
	5,  // 9: auth.UserLevelResponse.level:type_name -> auth.Level
	6,  // 10: auth.AuthService.Register:input_type -> auth.RegisterRequest
	8,  // 11: auth.AuthService.Redirect:input_type -> auth.RedirectRequest
	10, // 12: auth.AuthService.Callback:input_type -> auth.CallbackRequest
	12, // 13: auth.AuthService.GetMe:input_type -> auth.GetMeRequest
	14, // 14: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	15, // 15: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	17, // 16: auth.AuthService.RequestAccountSecurity:input_type -> auth.RequestAccountSecurityRequest
	18, // 17: auth.AuthService.VerifyAccountSecurity:input_type -> auth.VerifyAccountSecurityRequest
	19, // 18: auth.UserService.GetUser:input_type -> auth.GetUserRequest
	20, // 19: auth.UserService.UpdateProfile:input_type -> auth.UpdateProfileRequest
	21, // 20: auth.UserService.GetUserWallet:input_type -> auth.GetUserWalletRequest
	23, // 21: auth.UserService.GetUserLevel:input_type -> auth.GetUserLevelRequest
	25, // 22: auth.KYCService.SubmitKYC:input_type -> auth.SubmitKYCRequest
	27, // 23: auth.KYCService.GetKYCStatus:input_type -> auth.GetKYCStatusRequest
	28, // 24: auth.KYCService.VerifyBankAccount:input_type -> auth.VerifyBankAccountRequest
	7,  // 25: auth.AuthService.Register:output_type -> auth.RegisterResponse
	9,  // 26: auth.AuthService.Redirect:output_type -> auth.RedirectResponse
	11, // 27: auth.AuthService.Callback:output_type -> auth.CallbackResponse
	13, // 28: auth.AuthService.GetMe:output_type -> auth.UserResponse
	31, // 29: auth.AuthService.Logout:output_type -> google.protobuf.Empty
	16, // 30: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	31, // 31: auth.AuthService.RequestAccountSecurity:output_type -> google.protobuf.Empty
	31, // 32: auth.AuthService.VerifyAccountSecurity:output_type -> google.protobuf.Empty
	0,  // 33: auth.UserService.GetUser:output_type -> auth.User
	0,  // 34: auth.UserService.UpdateProfile:output_type -> auth.User
	22, // 35: auth.UserService.GetUserWallet:output_type -> auth.UserWalletResponse
	24, // 36: auth.UserService.GetUserLevel:output_type -> auth.UserLevelResponse
	26, // 37: auth.KYCService.SubmitKYC:output_type -> auth.KYCResponse
	26, // 38: auth.KYCService.GetKYCStatus:output_type -> auth.KYCResponse
	29, // 39: auth.KYCService.VerifyBankAccount:output_type -> auth.BankAccountResponse
	25, // [25:40] is the sub-list for method output_type
	10, // [10:25] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
