// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: financial.proto

package financial

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_financial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // VARCHAR PK like TR-xxxxx
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"` // deposit, withdraw
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Token         int64                  `protobuf:"varint,7,opt,name=token,proto3" json:"token,omitempty"`
	RefId         int64                  `protobuf:"varint,8,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	PayableType   string                 `protobuf:"bytes,9,opt,name=payable_type,json=payableType,proto3" json:"payable_type,omitempty"`
	PayableId     uint64                 `protobuf:"varint,10,opt,name=payable_id,json=payableId,proto3" json:"payable_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_financial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Transaction) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Transaction) GetToken() int64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *Transaction) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *Transaction) GetPayableType() string {
	if x != nil {
		return x.PayableType
	}
	return ""
}

func (x *Transaction) GetPayableId() uint64 {
	if x != nil {
		return x.PayableId
	}
	return 0
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefId         int64                  `protobuf:"varint,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	CardPan       string                 `protobuf:"bytes,4,opt,name=card_pan,json=cardPan,proto3" json:"card_pan,omitempty"`
	Gateway       string                 `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Product       string                 `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_financial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{2}
}

func (x *Payment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *Payment) GetCardPan() string {
	if x != nil {
		return x.CardPan
	}
	return ""
}

func (x *Payment) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Image         *string                `protobuf:"bytes,6,opt,name=image,proto3,oneof" json:"image,omitempty"` // URL or null
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_financial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{3}
}

func (x *Package) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Package) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Package) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Package) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Package) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *Package) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // integer quantity of units
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`    // psc, irr, red, blue, yellow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_financial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"` // Parsian payment URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_financial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type HandleCallbackRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status           int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // Parsian status code (0 indicates success)
	Token            int64                  `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
	Rrn              int64                  `protobuf:"varint,4,opt,name=rrn,proto3" json:"rrn,omitempty"`                                                                                                                            // Reference number
	CardMaskPan      string                 `protobuf:"bytes,5,opt,name=card_mask_pan,json=cardMaskPan,proto3" json:"card_mask_pan,omitempty"`                                                                                        // Masked card number
	AdditionalParams map[string]string      `protobuf:"bytes,6,rep,name=additional_params,json=additionalParams,proto3" json:"additional_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Other gateway fields
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandleCallbackRequest) Reset() {
	*x = HandleCallbackRequest{}
	mi := &file_financial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCallbackRequest) ProtoMessage() {}

func (x *HandleCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCallbackRequest.ProtoReflect.Descriptor instead.
func (*HandleCallbackRequest) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{6}
}

func (x *HandleCallbackRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *HandleCallbackRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleCallbackRequest) GetToken() int64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *HandleCallbackRequest) GetRrn() int64 {
	if x != nil {
		return x.Rrn
	}
	return 0
}

func (x *HandleCallbackRequest) GetCardMaskPan() string {
	if x != nil {
		return x.CardMaskPan
	}
	return ""
}

func (x *HandleCallbackRequest) GetAdditionalParams() map[string]string {
	if x != nil {
		return x.AdditionalParams
	}
	return nil
}

type HandleCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"` // Frontend verification URL with query params
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleCallbackResponse) Reset() {
	*x = HandleCallbackResponse{}
	mi := &file_financial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCallbackResponse) ProtoMessage() {}

func (x *HandleCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCallbackResponse.ProtoReflect.Descriptor instead.
func (*HandleCallbackResponse) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{7}
}

func (x *HandleCallbackResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GetStorePackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"` // At least 2 package codes required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorePackagesRequest) Reset() {
	*x = GetStorePackagesRequest{}
	mi := &file_financial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorePackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorePackagesRequest) ProtoMessage() {}

func (x *GetStorePackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorePackagesRequest.ProtoReflect.Descriptor instead.
func (*GetStorePackagesRequest) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{8}
}

func (x *GetStorePackagesRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type GetStorePackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*Package             `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorePackagesResponse) Reset() {
	*x = GetStorePackagesResponse{}
	mi := &file_financial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorePackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorePackagesResponse) ProtoMessage() {}

func (x *GetStorePackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorePackagesResponse.ProtoReflect.Descriptor instead.
func (*GetStorePackagesResponse) Descriptor() ([]byte, []int) {
	return file_financial_proto_rawDescGZIP(), []int{9}
}

func (x *GetStorePackagesResponse) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_financial_proto protoreflect.FileDescriptor

const file_financial_proto_rawDesc = "" +
	"\n" +
	"\x0ffinancial.proto\x12\tfinancial\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xec\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf9\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x14\n" +
	"\x05token\x18\a \x01(\x03R\x05token\x12\x15\n" +
	"\x06ref_id\x18\b \x01(\x03R\x05refId\x12!\n" +
	"\fpayable_type\x18\t \x01(\tR\vpayableType\x12\x1d\n" +
	"\n" +
	"payable_id\x18\n" +
	" \x01(\x04R\tpayableId\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa6\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06ref_id\x18\x03 \x01(\x03R\x05refId\x12\x19\n" +
	"\bcard_pan\x18\x04 \x01(\tR\acardPan\x12\x18\n" +
	"\agateway\x18\x05 \x01(\tR\agateway\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x18\n" +
	"\aproduct\x18\a \x01(\tR\aproduct\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x01\n" +
	"\aPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x12\x19\n" +
	"\x05image\x18\x06 \x01(\tH\x00R\x05image\x88\x01\x01B\b\n" +
	"\x06_image\"[\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\")\n" +
	"\x13CreateOrderResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"\xc0\x02\n" +
	"\x15HandleCallbackRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05token\x18\x03 \x01(\x03R\x05token\x12\x10\n" +
	"\x03rrn\x18\x04 \x01(\x03R\x03rrn\x12\"\n" +
	"\rcard_mask_pan\x18\x05 \x01(\tR\vcardMaskPan\x12c\n" +
	"\x11additional_params\x18\x06 \x03(\v26.financial.HandleCallbackRequest.AdditionalParamsEntryR\x10additionalParams\x1aC\n" +
	"\x15AdditionalParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x16HandleCallbackResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\"/\n" +
	"\x17GetStorePackagesRequest\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"J\n" +
	"\x18GetStorePackagesResponse\x12.\n" +
	"\bpackages\x18\x01 \x03(\v2\x12.financial.PackageR\bpackages2\xb3\x01\n" +
	"\fOrderService\x12L\n" +
	"\vCreateOrder\x12\x1d.financial.CreateOrderRequest\x1a\x1e.financial.CreateOrderResponse\x12U\n" +
	"\x0eHandleCallback\x12 .financial.HandleCallbackRequest\x1a!.financial.HandleCallbackResponse2k\n" +
	"\fStoreService\x12[\n" +
	"\x10GetStorePackages\x12\".financial.GetStorePackagesRequest\x1a#.financial.GetStorePackagesResponseB\x1dZ\x1bmetargb/shared/pb/financialb\x06proto3"

var (
	file_financial_proto_rawDescOnce sync.Once
	file_financial_proto_rawDescData []byte
)

func file_financial_proto_rawDescGZIP() []byte {
	file_financial_proto_rawDescOnce.Do(func() {
		file_financial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_financial_proto_rawDesc), len(file_financial_proto_rawDesc)))
	})
	return file_financial_proto_rawDescData
}

var file_financial_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_financial_proto_goTypes = []any{
	(*Order)(nil),                    // 0: financial.Order
	(*Transaction)(nil),              // 1: financial.Transaction
	(*Payment)(nil),                  // 2: financial.Payment
	(*Package)(nil),                  // 3: financial.Package
	(*CreateOrderRequest)(nil),       // 4: financial.CreateOrderRequest
	(*CreateOrderResponse)(nil),      // 5: financial.CreateOrderResponse
	(*HandleCallbackRequest)(nil),    // 6: financial.HandleCallbackRequest
	(*HandleCallbackResponse)(nil),   // 7: financial.HandleCallbackResponse
	(*GetStorePackagesRequest)(nil),  // 8: financial.GetStorePackagesRequest
	(*GetStorePackagesResponse)(nil), // 9: financial.GetStorePackagesResponse
	nil,                              // 10: financial.HandleCallbackRequest.AdditionalParamsEntry
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_financial_proto_depIdxs = []int32{
	11, // 0: financial.Order.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: financial.Order.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: financial.Transaction.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: financial.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	11, // 4: financial.Payment.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: financial.Payment.updated_at:type_name -> google.protobuf.Timestamp
	10, // 6: financial.HandleCallbackRequest.additional_params:type_name -> financial.HandleCallbackRequest.AdditionalParamsEntry
	3,  // 7: financial.GetStorePackagesResponse.packages:type_name -> financial.Package
	4,  // 8: financial.OrderService.CreateOrder:input_type -> financial.CreateOrderRequest
	6,  // 9: financial.OrderService.HandleCallback:input_type -> financial.HandleCallbackRequest
	8,  // 10: financial.StoreService.GetStorePackages:input_type -> financial.GetStorePackagesRequest
	5,  // 11: financial.OrderService.CreateOrder:output_type -> financial.CreateOrderResponse
	7,  // 12: financial.OrderService.HandleCallback:output_type -> financial.HandleCallbackResponse
	9,  // 13: financial.StoreService.GetStorePackages:output_type -> financial.GetStorePackagesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_financial_proto_init() }
func file_financial_proto_init() {
	if File_financial_proto != nil {
		return
	}
	file_financial_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_financial_proto_rawDesc), len(file_financial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_financial_proto_goTypes,
		DependencyIndexes: file_financial_proto_depIdxs,
		MessageInfos:      file_financial_proto_msgTypes,
	}.Build()
	File_financial_proto = out.File
	file_financial_proto_goTypes = nil
	file_financial_proto_depIdxs = nil
}
